./configure \
    --prefix $HOME/local \
    --without-all \
    --with-x-toolkit=lucid \
    --with-jpeg \
    --with-gif \
    --with-png \
    --with-rsvg \
    --with-xml2 \
    --with-xft \
    --with-gnutls
